### ISSUE TITLE
edge_flag

### ISSUE THREAD

**Issue by aaaking** [ikew0ng/SwipeBackLayout#142]
Caused by: java.lang.NumberFormatException: For input string: "50.0dip"
                                                                           at java.lang.Integer.parseInt(Integer.java:521)
                                                                           at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
                                                                           at android.content.res.TypedArray.getInt(TypedArray.java:367)
                                                                           at me.imid.swipebacklayout.lib.SwipeBackLayout.<init>(SwipeBackLayout.java:142)
                                                                           at me.imid.swipebacklayout.lib.SwipeBackLayout.<init>(SwipeBackLayout.java:129)

**Comment by aaaking** [comment]
older android studio compile ok, but when use android studio 3.0, it reports this error as soon as launch app

**Comment by rafaelekol** [comment]
I have same issue

**Comment by aaaking** [comment]
android studio 3.0 changes very much, have you fixed this problem?, How?

**Comment by panpf** [comment]
我 clone 了源码，用 3.0 版本的插件重新编译了一遍，然后本地依赖自己生成的 aar 包就可以正常使用了

I clone the source code, with the 3.0 version of the plug-in recompile it again, and then rely on their local generated aar package can be used normally

**Comment by aaaking** [comment]
@panpf 不错，可行，但是希望作者能更新下这个库
it works, while I hope the author may update this project

**Comment by panpf** [comment]
我已经给作者发邮件请求更新了

I have sent an email to the author requesting an update

**Comment by jimbray** [comment]
@panpf It works by use your way. THX.

**Comment by aaaking** [comment]
Can you release a new version? version 1.0.0 still has this problem
