### ISSUE TITLE
null point exception

### ISSUE THREAD

**Issue by aaaking** [ikew0ng/SwipeBackLayout#150]
this npe is just like this below:

STACK_TRACE=java.lang.NullPointerException: Attempt to read from null array
	at me.imid.swipebacklayout.lib.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1112)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onInterceptTouchEvent(SwipeBackLayout.java:365)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3241)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4865)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4404)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4461)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6690)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6664)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6625)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6819)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6764)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6847)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
	at android.view.Choreographer.doCallbacks(Choreographer.java:742)
	at android.view.Choreographer.doFrame(Choreographer.java:668)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6605)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)

have you any idea about this?

**Comment by wpq2014** [comment]
我这边bugly也统计到上面的问题了，看了下源码可以对数组判空，但是不敢轻易改作者源码，希望作者有空可以优化一下🙏🙏
