### ISSUE TITLE
pointerIndex out of range

### ISSUE THREAD

**Issue by nierongcheng** [ikew0ng/SwipeBackLayout#162]
java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2203)
	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:510)
	at me.imid.swipebacklayout.lib.c.b(ViewDragHelper.java:1226)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onTouchEvent(SwipeBackLayout.java:378)
	at android.view.View.dispatchTouchEvent(View.java:11788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2647)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3548)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
	at android.view.View.dispatchPointerEvent(View.java:12027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5240)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5030)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4690)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4571)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4747)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4563)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4544)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7121)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7095)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7056)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7277)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:379)
	at android.os.Looper.loop(Looper.java:144)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by h923745834** [comment]
@ @ikew0ng 这个问题虽说的系统问题，你能否修复一下呢？try{}catch()一下。至少不要程序崩溃啊

**Comment by ZhuLeon** [comment]
我是这么解决的：
![Jietu20190520-103140](https://user-images.githubusercontent.com/5566667/57993204-855e5a80-7aea-11e9-8473-99a3ec5ff1bb.jpg)
