### ISSUE TITLE
NullPointerException when Activity finished

### ISSUE THREAD

**Issue by mariotaku** [ikew0ng/SwipeBackLayout#5]
set layerType to ViewCompat.LAYER_TYPE_NONE in SwipeBackLayout$ViewDragCallback.onViewDragStateChanged(int) causes this problem.

you can comment out following lines to avoid crash.

```
        if (state == ViewDragHelper.STATE_IDLE) {
            ViewCompat.setLayerType(SwipeBackLayout.this, ViewCompat.LAYER_TYPE_NONE, null);
        } else if (state == ViewDragHelper.STATE_SETTLING) {
            ViewCompat.setLayerType(SwipeBackLayout.this, ViewCompat.LAYER_TYPE_HARDWARE, null);
        }
```

**Comment by aneeshATgithub** [comment]
Hello, please give any fix on this issue,

This crash occurs when I once logout from google login from may app and do login second time.
First time, there is no crashes. and second time , while google login app crashes and getting the following log from Android Monitor in Android Studio

FATAL EXCEPTION: main
Process: com.brainpodium.zonmart, PID: 16935
java.lang.NullPointerException
at android.view.GLES20RenderLayer.start(GLES20RenderLayer.java:112)
at android.view.GLES20RenderLayer.start(GLES20RenderLayer.java:103)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:544)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
