### ISSUE TITLE
ArrayIndexOutOfBoundsException when combine chrisbanes/PhotoView and SwipeBackLayout

### ISSUE THREAD

**Issue by djj0809** [ikew0ng/SwipeBackLayout#9]
Exception stack is 

``` java
        java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at me.imid.swipebacklayout.lib.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1084)
        at me.imid.swipebacklayout.lib.SwipeBackLayout.onInterceptTouchEvent(SwipeBackLayout.java:277)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1851)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1970)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1410)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2509)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1912)
        at android.view.View.dispatchPointerEvent(View.java:7333)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3239)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3184)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4237)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4216)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4308)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:163)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4287)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4327)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
        at android.view.Choreographer.doCallbacks(Choreographer.java:555)
        at android.view.Choreographer.doFrame(Choreographer.java:523)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4866)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)

```

**Comment by Vieuma** [comment]
I know it's an old thread, but any update on this? I also get this exact same issue. Thanks!
